TransHub/TransHub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from TransHub import settings
from main.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('cargo/', include('cargo.urls', namespace='cargo')),
    path('transport/', include('transport.urls', namespace='transport')),
    path('', include('main.urls')),
]
"""
if settings.DEBUG:
    import debug_toolbar
    urlpatterns=[
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    """
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TransHub/main/urls.py
from django.urls import path,include
from .views import *

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('logout/', logout_user, name='logout'),
    path('log/', MainLogin.as_view(), name='log_good'),
    path('about/', About.as_view(), name='about'),
    path('about_cargo/', About_Cargo.as_view(), name='about_cargo'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('take_cargo/', take_cargo, name='take_cargo'),
    path('freeze_cargo/', freeze_cargo_tr, name='freeze_cargo'),
    path('delivered_cargo/', delivered_cargo, name='delivered_cargo'),
    path('unfreeze_cargo/', un_freeze_cargo_tr, name='un_freeze'),
    path('unfreeze_tr/', un_freeze_tr, name='un_freeze_tr'),
    path('create_docs/', create_docs, name='create_docs'),
    path('my_docs/', MYDoc.as_view(), name='my_doc'),
    path('download/<str:file_type>/<int:event_id>/',download_file, name='download_file'),

]

TransHub/users/urls.py
from django.urls import path,include
from django.views.decorators.cache import cache_page
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .views import *

app_name = 'users'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('rev/', ReviewView.as_view(), name='rev'),
    path('com/', ComplaintView.as_view(), name='com'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('profile/', ProfileUser.as_view(), name='profile'),
    path('profiles/', user_list, name='user_list'),
    path('users/<int:user_id>/', user_detail, name='user_detail'),

    path('password-change/', UserPasswordChange.as_view(), name="password_change"),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name="password_change_done"),

    path('password-reset/',
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),

]

TransHub/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
class User(AbstractUser):
    ROLE_CHOICES = [
        ('SHIPPER', 'Відправник вантажу'),
        ('TRANSPORTER', 'Перевізник'),
        ('FORWARD', 'Експедитор'),
    ]

    role = models.CharField(max_length=20, choices=ROLE_CHOICES)
    about = models.TextField(blank=True, null=True)
    third_name = models.CharField(max_length=100, blank=True, null=True)
    activity_directions = models.ManyToManyField('ActivityDirection', related_name='users')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True, verbose_name="Фото")
    rating = models.DecimalField(max_digits=5, decimal_places=2, default=50)
    tel = models.BigIntegerField(validators=[MinValueValidator(1000000000), MaxValueValidator(999999999999)], null=True)
    name_company = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.username

    def get_absolute_url2(self):
        return reverse('post', kwargs={"name_slug": self.username})

    def get_full_name(self):
        return f"{self.last_name} {self.first_name} {self.third_name}"

    def update_rating(self, target_user):
        reviews = Review.objects.filter(target_user=target_user)
        complaints = Complaint.objects.filter(target_user=target_user).count()

        if reviews.exists():
            avg_rating = sum([review.rating for review in reviews]) / reviews.count()
            print(avg_rating)
            self.rating = (avg_rating / 5) * 100 - (complaints * 5)
            print(self.rating)
            self.rating = max(0, min(self.rating, 100))  # Обмежити від 0 до 100
        else:
            self.rating = 50.00 - (complaints * 5)  # Початковий рейтинг
        self.save()

class ActivityDirection(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Review(models.Model):
    user = models.ForeignKey(get_user_model(), related_name='reviews', on_delete=models.CASCADE)
    target_user = models.ForeignKey(get_user_model(), related_name='rev_target_user',verbose_name="Користувач якому присвячуется Відгук", on_delete=models.CASCADE)
    rating = models.IntegerField(verbose_name="Рейтинг")
    comment = models.TextField(verbose_name="Опис")
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.rating} от {self.user} до  {self.target_user}: {self.comment}  "

    def get_absolute_url(self):
        return reverse('log_good')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        target_user = self.target_user
        self.target_user.update_rating(target_user)

class Complaint(models.Model):
    user = models.ForeignKey(get_user_model(), related_name='complaints', on_delete=models.CASCADE)
    target_user = models.ForeignKey(get_user_model(), related_name='com_target_user',verbose_name="Користувач якому присвячуется Скарга", on_delete=models.CASCADE)
    description = models.TextField(verbose_name="Опис")
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Скарга  від {self.user} до {self.target_user} з приводу {self.description}"

    def get_absolute_url(self):
        return reverse('log_good')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        target_user = self.target_user
        self.target_user.update_rating(target_user)

TransHub/users/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse,HttpResponseNotFound, Http404
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from django.views.generic import ListView, DetailView, FormView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.db.models import Count, Q, F

from .models import *
from main.models import Event
from .forms import *
from .utils import *
# Create your views here.

class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:profile')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Реєстрація')
        return dict(list(context.items())+list(c_def.items()))

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    context_object_name = 'users'
    template_name = 'users/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Авторизація')
        return dict(list(context.items())+list(c_def.items()))


def logout_user(request):
    logout(request)
    return redirect('home')

class ProfileUser(LoginRequiredMixin,DataMixin,UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'

    def get_object(self):
        return self.request.user
    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Профіль')
        return dict(list(context.items())+list(c_def.items()))

class ProfilesUser(LoginRequiredMixin,DataMixin, ListView):
    model = get_user_model()
    template_name = 'users/profiles.html'
    context_object_name = 'users'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Профілі')
        return dict(list(context.items())+list(c_def.items()))

    def get_queryset(self):
        return get_user_model().objects.all()

class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"


class ReviewView(LoginRequiredMixin,DataMixin, CreateView):
    form_class = ReviewForm
    template_name = 'users/rev_add.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Відгук')
        return dict(list(context.items())+list(c_def.items()))

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['current_user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        w = form.save(commit=False)
        w.user = self.request.user
        return super().form_valid(form)


class ComplaintView(LoginRequiredMixin, DataMixin, CreateView):
    form_class = ComplaintForm
    template_name = 'users/com_add.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Скарга')
        return dict(list(context.items())+list(c_def.items()))

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['current_user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        w = form.save(commit=False)
        w.user = self.request.user
        return super().form_valid(form)


def user_list(request):
    query = request.GET.get('q')
    if query:
        users = User.objects.filter(models.Q(username__icontains=query) | models.Q(email__icontains=query))
    else:
        users = User.objects.all()

    users = users.annotate(
        ev_count=Count("author__event_cargo", distinct=True)+Count("author1__event_transport", distinct=True),
        review_count=Count('rev_target_user', distinct=True),
        complaint_count=Count('com_target_user', distinct=True)
    )
    return render(request, 'users/user_list.html', {'users': users})


def user_detail(request, user_id):
    user2 = get_object_or_404(User, id=user_id)
    reviews = Review.objects.filter(target_user=user2)
    claims = Complaint.objects.filter(target_user=user2)  # Предполагаем, что поле связи с User называется `user`
    ev_count = Event.objects.filter(cargo__author=user2).count() + Event.objects.filter(transport__author=user2).count()
    return render(request, 'users/user_detail.html', {
        'user2': user2,
        'reviews': reviews,
        'claims': claims,
        'ev_count': ev_count
    })

TransHub/users/templates/users/com_add.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container mx-5">
<form method="post" enctype="multipart/form-data">

    <h1>{{title}}</h1>
    {% csrf_token %}
<div class="form-error">{{form.non_field_errors}}</div>
{%for f in form%}
     <div class="col-md-6">
    {{ f.label_tag }}
    {{ f }}
    <div class="form-error">{{f.errors}}</div>
    </div>
{% endfor%}

   <button type="submit" class="btn btn-primary">Додати</button>
</form>
</div>
{% endblock %}

TransHub/users/templates/users/login.html
{% extends 'main/defbase.html' %}

{% block content %}

<main class="form-signin m-auto mt-5 " style="width:320px">
    <div class="container" > </div>
<h1 class="h3 mb-3 fw-normal">{{title}}</h1>

<form method="post">

{% csrf_token %}
<input type="hidden" name="next" value="{{ next }}"/>
<div class="form-error">{{ form.non_field_errors}}</div>
    {%for f in form%}
    <div class="form-floating">
        {{f}}
    <label for="{{f.id_for_label}}">{{f.label}}:</label>
    <div class="form-error">{{f.errors}}</div>
    </div>
{% endfor%}

    <button class="btn btn-primary w-100 my-2 " type="submit">Sign in</button>
    root <br>
    K4mD337Ffd
    <hr class="my-4">
    </form>
    <p><a href="{% url 'users:password_reset' %}">Забули пароль?</a></p>

</main>

{% endblock %}

TransHub/users/templates/users/password_change_done.html
{% extends 'main/defbase.html' %}

{% block content %}
<h1>Пароль успешно изменен!</h1>

<p>Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

TransHub/users/templates/users/password_change_form.html
{% extends 'main/defbase.html' %}

{% block content %}
<h1>Изменение пароля</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Изменить пароль</button></p>
</form>

{% endblock %}

TransHub/users/templates/users/password_reset_complete.html
{% extends 'main/defbase.html' %}

{% block content %}
<h1>Пароль изменен</h1>

<p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
  <a href="{% url 'users:login' %}">входа в систему</a>.</p>

{% endblock %}

TransHub/users/templates/users/password_reset_confirm.html
{% extends 'main/defbase.html' %}

{% block content %}
<h1>Новый пароль</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Сохранить</button></p>
</form>

{% endblock %}

TransHub/users/templates/users/password_reset_done.html
{% extends "main/defbase.html" %}
{% load i18n %}

{% block content %}
<h1>Сброс пароля</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

TransHub/users/templates/users/password_reset_form.html
{% extends 'main/defbase.html' %}

{% block content %}
<h1>Восстановление пароля</h1>

<form method="post">
    {% csrf_token %}
{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <p><button type="submit">Сбросить по E-mail</button></p>
</form>

{% endblock %}

TransHub/users/templates/users/profile.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="container w-50" align="left" >
<h1 align="center">{{title}}</h1>
<form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
<input type="hidden" name="next" value="{{ next }}"/>

    <div class="form-floating">
                {{ form.username }}
                <label for="{{ form.username.id_for_label }}">Ім'я користувача:</label>
                <div class="form-error">{{ form.username.errors }}</div>
            </div>
 <div class="row">
      <div class="col-md-6">
            <div class="form-floating">
                {{ form.email }}
                <label for="{{ form.email.id_for_label }}">Email:</label>
                <div class="form-error">{{ form.email.errors }}</div>
            </div>
          </div>
     <div class="col-md-6">
            <div class="form-floating">
                {{ form.tel }}
                {{ form.tel.label_tag }}
                <div class="form-error">{{ form.tel.errors }}</div>
            </div>
          </div>
 </div>

 <div class="row">
      <div class="col-md-4">
            <div class="form-floating">
                {{ form.first_name }}
                <label for="{{ form.first_name.id_for_label }}">Ім'я:</label>
                <div class="form-error">{{ form.first_name.errors }}</div>
            </div>
          </div>
 <div class="col-md-4">
            <div class="form-floating">
                {{ form.last_name }}
                <label for="{{ form.last_name.id_for_label }}">Прізвище:</label>
                <div class="form-error">{{ form.last_name.errors }}</div>
            </div>
     </div>
 <div class="col-md-4">
            <div class="form-floating">
                {{ form.third_name }}
                <label for="{{ form.third_name.id_for_label }}">По батькові:</label>
                <div class="form-error">{{ form.third_name.errors }}</div>
            </div>
      </div>
</div>
     <div class="row">
<div class="col-md-6">
            <div class="form-floating">
                {{ form.about }}
                <label for="{{ form.about.id_for_label }}">Про себе:</label>
                <div class="form-error">{{ form.about.errors }}</div>
            </div>
     </div>
     <div class="col-md-6">
            <div class="form-floating">
                {{ form.name_company}}
                 {{ form.name_company.label_tag }}
                <div class="form-error">{{form.name_company.errors}}</div>
            </div>
      </div>
</div>
            <div class="form-floating">
                {{ form.role }}
                <label for="{{ form.role.id_for_label }}">Роль:</label>
                <div class="form-error">{{ form.role.errors }}</div>
            </div>
            <div class="form-floating">
                {{ form.photo }}

                <div class="form-error">{{ form.photo.errors }}</div>
            </div>

            <div class="form-group">
    {{ form.activity_directions.label_tag }}
    <div class="form-check-inline-container">
        {% for checkbox in form.activity_directions %}
            <div class="form-check-inline">
                {{ checkbox.tag }} {{ checkbox.choice_label }}
            </div>
        {% endfor %}
    </div>
    <div class="form-error">{{ form.activity_directions.errors }}</div>
</div>
<div align="center">
      <button class="btn btn-primary w-50 " type="submit" >Зберегти</button>
    </div>
</form>

<p align="center"><a href="{% url 'users:password_change' %}">Змінити пароль</a></p>
</div>
<!-- 
<div class="w-25 ms-5" >
    <div class="row">
        <div class="col-md-4">
            <div style="width:100px ; height:100px;">
                <a href="#" class="text-decoration-none"><img width="80" height="80" src="{% static 'main/images/rev.png' %}"> Кількість відгуків: {{ countrev.count }} </a>
            </div>
        </div>
        <div class="col-md-4">
            <div style="width:100px ; height:100px;">
                <a href="#" class="text-decoration-none"><img width="80" height="80" src="{% static 'main/images/comp.png' %}"> Кількість скарг: {{ countcom.count }}</a>
            </div>
        </div>
        <div class="col-md-4">
            <div style="width:100px ; height:100px;">
                <a href="#" class="text-decoration-none"><img width="80" height="80" src="{% static 'main/images/my_rev_com.png' %}"><p>Мої відгуки/скарги</p></a>
            </div>
        </div>
    </div>

</div>
-->

{% endblock %}

TransHub/users/templates/users/profiles.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="w-75 ms-4">
<h1>{{title}}</h1>

    <table>
        <thead>
        <tr>
            <th>Юзернейм</th>
             <th>Останній Логін</th>
             <th>ПІБ</th>
            <th>Про себе</th>
             <th>Адреса Пошти</th>
             <th>Роль</th>
             <th>Фото</th>
            <th>Рейтинг користувача</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users%}
        <tr>
            <td>{{ user.username}}</td>
            <td>{{ user.last_login}}</td>
            <td>{{ user.first_name}}
            {{ user.last_name}}
            {{ user.third_name}}</td>
            <td>{{ user.about}}</td>
            <td>{{ user.email}}</td>
            <td>{{ user.role}}</td>
            <td>{% if user.photo %}
            <p><img alt="" width="32" height="32" class="rounded-circle me-2" src="{{user.photo.url}}"></p>
        {% else %}
           <p>Без фото</p>
          {% endif %}
            </td>
            <td>{{ user.rating}} </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>


</div >

{% endblock %}

TransHub/users/templates/users/rev.html
<ul class="w-25">
    <li>
        {% for a in rev_my %}
        <p>{{a}}</p>
        <br>
        {% endfor %}
    </li>
    <li>
        {% for a in rev_for_me %}
        <p>{{a}}</p>
        <br>
        {% endfor %}
    </li>
    <li>
        {% for a in com_my %}
        <p>{{a}}</p>
        <br>
        {% endfor %}
    </li>
    <li>
        {% if com_for_me %}
            {% for a in com_for_me %}
            <p>{{a}}</p>
            <br>
            {% endfor %}
        {% else %}
        <p>fdgfhfdh</p>
        {% endif %}
    </li>
</ul>

TransHub/users/templates/users/user_detail.html
{% extends 'main/base.html' %}
{% load static %}
{% load main_extras %}

{% block content %}

<style>
 .container2 {
    background-color: white;
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
}

.main-content {
    flex: 2;
    padding-right: 20px;
}
.sidebar5 {
    flex: 1;
    padding-left: 20px;
    max-width: 300px;
}

.sidebar5 h4 {
    margin-top: 0;
}

.sidebar5 ul {
    list-style-type: none;
    padding: 0;
}

.sidebar5 li {
    margin-bottom: 10px;
}
.container2 {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
}
</style>


<div class=" container2 m-2">
     <div class="main-content">
    <h4>{{ user2.get_full_name }}</h4>
        {% if user2.photo %}
            <p><img alt="" width="100" height="100" class="rounded-circle me-2" src="{{user2.photo.url}}"></p>
        {% else %}
        <img src="{% static 'main/images/def_logo.webp' %}" alt="" width="100" height="100" class="rounded-circle me-2">
        {% endif %}
    <div class="company">
        <strong>Компанія:</strong> {{ user2.name_company }}
        <div class="star-rating">
                            <div class="stars-outer">
                                <div class="stars-inner" style="width: {{ user2.rating|floatformat:0 }}%;"></div>
                            </div>
                        </div>
        </div>

    <p><strong>О користувачі:</strong>
         {% if user2.about %}
        {{ user2.about }}
    {% else %}
          Немає інформації
        {% endif %}
    </p>
    <p><strong>Телефон:</strong>
    {% if user2.tel %}
        +{{ user2.tel }}
    {% else %}
          Немає інформації
        {% endif %}
        <strong>Електронна Пошта:</strong>
    {% if user2.email %}
        {{ user2.email }}
    {% else %}
          Немає інформації
        {% endif %}
    </p>

    <p><strong>Роль:</strong> {{ user2.get_role_display }}</p>
    <p><strong>Кількість перевезень:</strong> {{ ev_count }}</p>
    <p><strong>Кількість відгуків:</strong> {{ reviews.count }}</p>
    <p><strong>Кількість скарг:</strong> {{ claims.count }}</p>

    <h4>Напрямки роботи:</h4>
    <ul>
        {% for direction in user2.activity_directions.all %}
            <li>{{ direction.name }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'users:user_list' %}">До списку користувачів</a>
 </div>
    <div class="sidebar5">
        <h4>Відгуки ({{ reviews.count }})</h4>
        <ul>
            {% for review in reviews %}
                <li>{{ review.user }} — {{ review.comment }} —
            <div class="star-rating">
                            <div class="stars-outer">
                                <div class="stars-inner" style="width: {{ review.rating|mul:20|floatformat:0 }}%;"></div>
                            </div>
                        </div>
                </li>
            {% endfor %}
        </ul>

        <h4>Скарги ({{ claims.count }})</h4>
        <ul>
            {% for claim in claims %}
                <li>{{ claim.description }} — <strong>Дата:</strong> {{ claim.date }}</li>
            {% endfor %}
        </ul>
    </div>


</div>
{% endblock %}

TransHub/users/templates/users/user_list.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<div class="container m-4">
<form method="get" action="{% url 'users:user_list' %}">
        <input style="width:300px" type="text" name="q" placeholder="Пошук по логіну або ел. пошті" value="{{ request.GET.q }}">
        <button type="submit" class="btn btn-secondary rounded-pill px-3">Пошук</button>
    </form>

<ul>
        {% for user in users %}
            <li>
                <h4>{{ user.get_full_name }} </h4>
                {% if user.photo %}
            <p><img alt="" width="50" height="50" class="rounded-circle me-2" src="{{user.photo.url}}"></p>
        {% else %}
        <img src="{% static 'main/images/def_logo.webp' %}" alt="" width="50" height="50" class="rounded-circle me-2">
        {% endif %}

<p><strong>Телефон:</strong>
    {% if user.tel %}
        +{{ user.tel }}
    {% else %}
          Немає інформації
        {% endif %}
      </p>
      <p>  <strong>Електронна Пошта:</strong>
    {% if user.email %}
        {{ user.email }}
    {% else %}
          Немає інформації
        {% endif %}
    </p>

                <div class="company">
                    <strong>Компанія:</strong> {{ user.name_company }}
                <div class="star-rating">
                        <div class="stars-outer">
                            <div class="stars-inner" style="width: {{ user.rating|floatformat:0 }}%;"></div>
                        </div>
                    </div>
                 </div>

                <p><strong>к. перевезень:</strong> {{ user.ev_count }}
                <strong>к. відгуків:</strong> {{ user.review_count }}
                <strong>к. скарг:</strong> {{ user.complaint_count }}</p>

                <a href="{% url 'users:user_detail' user.id %}">Детальніше</a>
            </li>

        {% endfor %}

    </ul>
   </div>
{% endblock %}