TransHub/TransHub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from TransHub import settings
from main.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('cargo/', include('cargo.urls', namespace='cargo')),
    path('transport/', include('transport.urls', namespace='transport')),
    path('', include('main.urls')),
]
"""
if settings.DEBUG:
    import debug_toolbar
    urlpatterns=[
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    """
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TransHub/cargo/urls.py
from django.urls import path,include
from .views import *
app_name = 'cargo'

urlpatterns = [
    path('add_cargo/', AddCargo.as_view(), name='add_cargo'),
    path('all_cargo/', AllCargo.as_view(), name='all_cargo'),
    path('my_cargo/', MYCargo.as_view(), name='my_cargo'),
    path('ajax/load-regions/', load_regions, name='load_regions'),
    path('ajax/load-cities/', load_cities, name='load_cities'),
    path('update/<int:pk>/', Cargo_update.as_view(), name='update'),
]

TransHub/main/urls.py
from django.urls import path,include
from .views import *

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('logout/', logout_user, name='logout'),
    path('log/', MainLogin.as_view(), name='log_good'),
    path('about/', About.as_view(), name='about'),
    path('about_cargo/', About_Cargo.as_view(), name='about_cargo'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('take_cargo/', take_cargo, name='take_cargo'),
    path('freeze_cargo/', freeze_cargo_tr, name='freeze_cargo'),
    path('delivered_cargo/', delivered_cargo, name='delivered_cargo'),
    path('unfreeze_cargo/', un_freeze_cargo_tr, name='un_freeze'),
    path('unfreeze_tr/', un_freeze_tr, name='un_freeze_tr'),
    path('create_docs/', create_docs, name='create_docs'),
    path('my_docs/', MYDoc.as_view(), name='my_doc'),
    path('download/<str:file_type>/<int:event_id>/',download_file, name='download_file'),

]

TransHub/transport/urls.py
from django.urls import path,include
from .views import *

app_name = 'transport'

urlpatterns = [
    path('add_transport/', AddTransport.as_view(), name='add_transport'),
    path('all_transport/', AllTransport.as_view(), name='all_transport'),
    path('my_transport/', MYTransport.as_view(), name='my_transport'),
    path('ajax/load-regions/', load_regions, name='load_regions'),
    path('ajax/load-cities/', load_cities, name='load_cities'),
    path('update/<int:pk>/', Transport_update.as_view(), name='update'),
    path('detail/<int:tr_pk>/', ShowTr.as_view(), name='detail'),
]

TransHub/users/urls.py
from django.urls import path,include
from django.views.decorators.cache import cache_page
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .views import *

app_name = 'users'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('rev/', ReviewView.as_view(), name='rev'),
    path('com/', ComplaintView.as_view(), name='com'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('profile/', ProfileUser.as_view(), name='profile'),
    path('profiles/', user_list, name='user_list'),
    path('users/<int:user_id>/', user_detail, name='user_detail'),

    path('password-change/', UserPasswordChange.as_view(), name="password_change"),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name="password_change_done"),

    path('password-reset/',
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),

]

TransHub/main/models.py
from django.db import models


class Country(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Region(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=10)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class City(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return self.name


from cargo.models import Cargo
from transport.models import Transport


class Event(models.Model):
    cargo = models.ForeignKey(Cargo, on_delete=models.CASCADE, related_name='event_cargo')
    transport = models.ForeignKey(Transport, on_delete=models.CASCADE, related_name='event_transport')
    event_date = models.DateField(auto_now_add=True)
    arrived = models.BooleanField(default=False)
    act_file = models.FileField(upload_to='documents/acts/', blank=True, null=True)
    invoice_file = models.FileField(upload_to='documents/invoices/', blank=True, null=True)


class Frozen(models.Model):
    cargo = models.ForeignKey(Cargo, on_delete=models.CASCADE, related_name='frozen_set')
    transport = models.ForeignKey(Transport, on_delete=models.CASCADE, related_name='frozen_set')
    frozen_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата - Час створення")

    def __str__(self):
        return f"Frozen cargo {self.cargo.id} with transport {self.transport.id}"

TransHub/main/forms.py
from django import forms
from .models import *
from captcha.fields import CaptchaField


class ContactForm(forms.Form):
    name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Електронна пошта', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    content = forms.CharField(label='Текст',widget=forms.Textarea(attrs={'class': 'form-input'}))

TransHub/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import logout
from django.views.generic import ListView, DetailView, CreateView, FormView, TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


from .forms import *
from .utils import *
import math

from django.http import FileResponse, Http404
import os



class Home(DataMixin, TemplateView):
    template_name = 'main/index.html'
    context_object_name = 'posts'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Головна Сторінка')
        return dict(list(context.items())+list(c_def.items()))

def logout_user(request):
    logout(request)
    return redirect('home')


class MainLogin(LoginRequiredMixin, DataMixin, TemplateView):
    template_name = 'main/log_good.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Головна сторінка')
        return dict(list(context.items())+list(c_def.items()))


class About(DataMixin, TemplateView):
    template_name = 'main/about.html'
    context_object_name = 'posts'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Про сайт')
        return dict(list(context.items())+list(c_def.items()))

class About_Cargo(DataMixin, TemplateView):
    template_name = 'main/about_cargo.html'
    context_object_name = 'posts'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='О перевезеннях')
        return dict(list(context.items())+list(c_def.items()))

class ContactFormView(DataMixin, FormView):
    form_class = ContactForm
    template_name = 'main/contact.html'
    success_url = reverse_lazy('home')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Зворотний зв'язок")
        return dict(list(context.items())+list(c_def.items()))

    def form_valid(self, form):
        print(form.cleaned_data)
        return redirect('home')


def take_cargo(request):
    cargo_id = request.POST.get('cargo_id')
    cargo = get_object_or_404(Cargo, id=cargo_id)
    frozen = get_object_or_404(Frozen, cargo=cargo)

    Event.objects.create(cargo=frozen.cargo, transport=frozen.transport,arrived=False)

    frozen.cargo.freeze = False
    frozen.transport.freeze = False
    frozen.cargo.status = "IN_TRANSIT"
    frozen.transport.status = 'IN_TRANSIT'
    frozen.cargo.save()
    frozen.transport.save()
    frozen.delete()

    return redirect('cargo:my_cargo')


def freeze_cargo_tr(request):
    cargo_id = request.POST.get('cargo_id')
    cargo = get_object_or_404(Cargo, id=cargo_id)
    transport_id = request.POST.get('transport_id')
    transport = get_object_or_404(Transport, id=transport_id, author=request.user)

    fr = Frozen.objects.create(
        cargo=cargo,
        transport=transport,
    )

    cargo.freeze = True
    transport.freeze = True
    cargo.save()
    transport.save()

    return redirect('transport:my_transport')

def un_freeze_cargo_tr(request):
    cargo_id = request.POST.get('cargo_id')
    cargo = get_object_or_404(Cargo, id=cargo_id)
    frozen = get_object_or_404(Frozen, cargo=cargo)

    frozen.cargo.freeze = False
    frozen.transport.freeze = False
    cargo.save()
    frozen.cargo.save()
    frozen.transport.save()

    frozen.delete()

    return redirect('cargo:my_cargo')
def un_freeze_tr(request):
    transport_id = request.POST.get('cargo_id')
    transport = get_object_or_404(Transport, id=transport_id)
    frozen = get_object_or_404(Frozen, transport=transport)

    frozen.cargo.freeze = False
    frozen.transport.freeze = False
    frozen.cargo.save()
    frozen.transport.save()

    frozen.delete()

    return redirect('transport:my_transport')

def delivered_cargo(request):
    cargo_id = request.POST.get('cargo_id')
    cargo = get_object_or_404(Cargo, id=cargo_id)
    event = get_object_or_404(Event, cargo=cargo)

    event.cargo.status = "DELIVERED"
    event.transport.status = 'Search'
    event.cargo.save()
    event.transport.save()
    event.arrived = True
    event.save()

    return redirect('cargo:my_cargo')


def create_docs(request):
    ev_id = request.POST.get('ev_id')
    event = get_object_or_404(Event, id=ev_id)

    car = event.cargo
    tr = event.transport
    replacements = {
        "[company_cargo]": car.author.name_company,
        "[cargo_fio]": f"{car.author.first_name} {car.author.last_name} {car.author.third_name}",
        "[company_transport]": tr.author.name_company,
        "[from]": f"{car.city_from}",
        "[to]": f"{car.city_to}",
        "[type]": tr.model,
        "[nomer]": tr.license_plate,
        "[nomer_act]": f'{event.id:07}',

        "[data]": event.event_date.strftime("%d.%m.%Y"),

        "[amaunt]": f'{car.amount}',
        "[amaunt_type]": f'_{car.currency}',
        "[transport_short_fio]": f" {tr.author.last_name} {tr.author.first_name[0]}. {tr.author.third_name[0]}.",
        "[cargo_short_fio]": f" {car.author.last_name} {car.author.first_name[0]}. {car.author.third_name[0]}.",
    }

    replace_docs(replacements, event.act_file)
    replace2_docs(replacements, event.invoice_file)
    return redirect('my_doc')

class MYDoc(LoginRequiredMixin, DataMixin, ListView):
    model = Event
    template_name = 'main/my_doc.html'
    context_object_name = 'events'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Мої документи')
        user_id = self.request.user.pk

        events_as_cargo_author = Event.objects.filter(cargo__author=user_id)
        events_as_transport_author = Event.objects.filter(transport__author=user_id)
        context.update({
            'events_as_cargo_author': events_as_cargo_author,
            'events_as_transport_author': events_as_transport_author,
            **c_def
        })
        return context


def download_file(request, file_type, event_id):
    event = get_object_or_404(Event, id=event_id)

    if file_type == 'act' and event.act_file:
        file_path = event.act_file.path
    elif file_type == 'invoice' and event.invoice_file:
        file_path = event.invoice_file.path
    else:
        raise Http404("Файл не знайден.")

    if not os.path.exists(file_path):
        raise Http404("Файл не знайден.")

    return FileResponse(open(file_path, 'rb'), as_attachment=True, filename=os.path.basename(file_path))

TransHub/main/templates/main/about_cargo.html
{% extends 'main/base.html' %}
{% block content %}

<div class="container mt-5">

<h1>{{title}}</h1>

    <h2>Рейтинг розраховується на основі середнього значення відгуків, а потім застосовується штраф за скарги. Для цього потрібно:</h2>
    <ul>
        <li>Знайти середній рейтинг відгуків.</li>
        <li>Перевести середній рейтинг у шкалу 0-100.</li>
        <li>Відняти штрафи за скарги (наприклад, 5 балів за кожну скаргу).</li>
    </ul>

    <div class="example">
        <p>Допустимо:</p>
        <ul>
            <li>У користувача 10 відгуків з оцінками: 5, 4, 5, 3, 4, 5, 2, 4, 5, 3.</li>
            <li>2 скарги, штраф за кожну — 5 балів.</li>
        </ul>

        <div class="calculation">
            <p><strong>Середній рейтинг:</strong></p>
            <p>
                <span>(5 + 4 + 5 + 3 + 4 + 5 + 2 + 4 + 5 + 3)</span> ÷ 10 = 4
            </p>

            <p><strong>Оцінка за відгуки:</strong></p>
            <p>
                4 ÷ 5 × 100 = <span>80</span>
            </p>

            <p><strong>Штраф за скарги:</strong></p>
            <p>
                80 − (2 × 5) = <span>70</span>
            </p>

            <p><strong>Підсумковий рейтинг користувача:</strong> <span>70 балів</span>.</p>
        </div>
    </div>
    </div>
{% endblock %}

TransHub/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="uk">
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'main/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'main/images/icon.png' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

        <style>
         .published-true {
            background-color: purple;
            color: white;
        }
        .published-false {
            background-color: red;
            color: white;
        }
        </style>
</head>
<body>
<!-- Sidebar слева -->

<nav class="fixed-top d-flex flex-nowrap flex-column flex-shrink-0 p-3 text-bg-dark z-3" style="width: 250px; height: 100%">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
       <img width="24" height="24" src="{% static 'main/images/icon.png' %}">
        <span class="fs-4" style="margin-left: 10px">TransHub</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li>
        <a href="{% url 'log_good' %}" class="text-white text-decoration-none ms-3" >
          <img width="30" height="30" src="{% static 'main/images/home.png' %}"> Головна
        </a>
      </li>

        <li >
          <button class="btn nav-link text-white" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="false">
           <img width="30" height="30" src="{% static 'main/images/cargo_home.png' %}"> Вантаж
          </button>
          <div class="collapse" id="home-collapse">
            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 ms-5 small">
              <li><a href="{% url 'cargo:add_cargo' %}" style="color: brown;" class="text-white text-decoration-none" ><img width="20" height="20" src="{% static 'main/images/add_cargo.png' %}">Додати вантаж</a></li>
              <li><a href="{% url 'cargo:all_cargo' %}" style="color: brown;" class="text-white text-decoration-none"><img width="20" height="20" src="{% static 'main/images/search_cargo.png' %}"> Пошук вантажу</a></li>
              <li><a href="{% url 'cargo:my_cargo' %}" style="color: brown;" class="text-white text-decoration-none "><img width="20" height="20" src="{% static 'main/images/m_c.png' %}"> Мій вантаж</a></li>
            </ul>
          </div>
        </li>
        <li >
          <button class="btn nav-link text-white" data-bs-toggle="collapse" data-bs-target="#tr-collapse" aria-expanded="false">
            <img width="30" height="30" src="{% static 'main/images/truk_home.png' %}"> Транспорт
          </button>
          <div class="collapse" id="tr-collapse">
            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 ms-5 small">
              <li><a href="{% url 'transport:add_transport' %}" style="color: brown;" class="text-white text-decoration-none" ><img width="20" height="20" src="{% static 'main/images/add_tr.png' %}">Додати транспорт</a></li>
              <li><a href="{% url 'transport:all_transport' %}" style="color: brown;" class="text-white text-decoration-none"><img width="20" height="20" src="{% static 'main/images/search_tr.png' %}"> Пошук транспорту</a></li>
              <li><a href="{% url 'transport:my_transport' %}" style="color: brown;" class="text-white text-decoration-none "><img width="20" height="20" src="{% static 'main/images/my_cargo.png' %}"> Мій транспорт</a></li>
            </ul>
          </div>
        </li>
        <li >
          <button class="btn nav-link text-white" data-bs-toggle="collapse" data-bs-target="#hz-collapse" aria-expanded="false">
            <img width="30" height="30" src="{% static 'main/images/zona.png' %}"> Зона надійності
          </button>
          <div class="collapse" id="hz-collapse">
            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 ms-5 small">
              <li><a href="{% url 'users:rev' %}" style="color: brown;" class="text-white text-decoration-none" ><img width="20" height="20" src="{% static 'main/images/rev.png' %}">Створити Відгук</a></li>
              <li><a href="{% url 'users:com' %}" style="color: brown;" class="text-white text-decoration-none"><img width="20" height="20" src="{% static 'main/images/comp.png' %}">Створити Скаргу</a></li>
              <li><a href="{% url 'users:user_list' %}" style="color: brown;" class="text-white text-decoration-none"><img width="20" height="20" src="{% static 'main/images/prof.png' %}">Користувачі</a></li>
            </ul>
          </div>
        </li>
        <li>
        <a href="{% url 'my_doc' %}" class="text-white text-decoration-none ms-3" >
          <img width="30" height="30" src="{% static 'main/images/doc.png' %}"> Мої Документи
        </a>
      </li>
    </ul>
	<br>
<div class="dropdown">
      <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        {% if user.photo %}
            <p><img alt="" width="32" height="32" class="rounded-circle me-2" src="{{user.photo.url}}"></p>
        {% else %}
        <img src="{% static 'main/images/def_logo.webp' %}" alt="" width="32" height="32" class="rounded-circle me-2">
        {% endif %}
        <strong>{{user.username}}</strong>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow" style="">
        <li><a class="dropdown-item" href="{% url 'users:profile' %}">Редагувати Профіль</a></li>
          <li><a class="dropdown-item" href="{% url 'users:user_detail' user.id %}">Мій Профіль</a></li>
        <li><hr class="dropdown-divider"></li>

        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Вийти</a></li>
      </ul>
    </div>

</nav>

<main style="padding-left: 250px; padding-bottom:60px">

		{% block breadcrumbs %}
		{% endblock %}


	{% block content %}
	{% endblock %}


</main>

  <div class=" fixed-bottom d-flex flex-wrap justify-content-center align-items-center border-top bg-white z-2" style="margin-left: 250px">
      <div class="col-md-5 d-flex align-items-center">
      <span class="mb-3 mb-md-0 text-body-secondary" >© 2024 TransHub;<a href="mailto:prigara@dlit.dp.ua">Написати на пошту Outlook</a> </span>
    </div>

    <ul class="nav col-md-3 justify-content-end list-unstyled d-flex me-5" >
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
  <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
</svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16">
  <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/>
</svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="https://t.me/kirprog9"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-telegram" viewBox="0 0 16 16">
  <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.287 5.906q-1.168.486-4.666 2.01-.567.225-.595.442c-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294q.39.01.868-.32 3.269-2.206 3.374-2.23c.05-.012.12-.026.166.016s.042.12.037.141c-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8 8 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629q.14.092.27.187c.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.4 1.4 0 0 0-.013-.315.34.34 0 0 0-.114-.217.53.53 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09"/>
</svg></a></li>
    </ul>
  </div>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>

</body>
</html>