TransHub/TransHub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from TransHub import settings
from main.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('cargo/', include('cargo.urls', namespace='cargo')),
    path('transport/', include('transport.urls', namespace='transport')),
    path('', include('main.urls')),
]
"""
if settings.DEBUG:
    import debug_toolbar
    urlpatterns=[
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    """
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TransHub/main/urls.py
from django.urls import path,include
from .views import *

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('logout/', logout_user, name='logout'),
    path('log/', MainLogin.as_view(), name='log_good'),
    path('about/', About.as_view(), name='about'),
    path('about_cargo/', About_Cargo.as_view(), name='about_cargo'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('take_cargo/', take_cargo, name='take_cargo'),
    path('freeze_cargo/', freeze_cargo_tr, name='freeze_cargo'),
    path('delivered_cargo/', delivered_cargo, name='delivered_cargo'),
    path('unfreeze_cargo/', un_freeze_cargo_tr, name='un_freeze'),
    path('unfreeze_tr/', un_freeze_tr, name='un_freeze_tr'),
    path('create_docs/', create_docs, name='create_docs'),
    path('my_docs/', MYDoc.as_view(), name='my_doc'),
    path('download/<str:file_type>/<int:event_id>/',download_file, name='download_file'),

]

TransHub/transport/urls.py
from django.urls import path,include
from .views import *

app_name = 'transport'

urlpatterns = [
    path('add_transport/', AddTransport.as_view(), name='add_transport'),
    path('all_transport/', AllTransport.as_view(), name='all_transport'),
    path('my_transport/', MYTransport.as_view(), name='my_transport'),
    path('ajax/load-regions/', load_regions, name='load_regions'),
    path('ajax/load-cities/', load_cities, name='load_cities'),
    path('update/<int:pk>/', Transport_update.as_view(), name='update'),
    path('detail/<int:tr_pk>/', ShowTr.as_view(), name='detail'),
]

TransHub/users/urls.py
from django.urls import path,include
from django.views.decorators.cache import cache_page
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .views import *

app_name = 'users'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('rev/', ReviewView.as_view(), name='rev'),
    path('com/', ComplaintView.as_view(), name='com'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('profile/', ProfileUser.as_view(), name='profile'),
    path('profiles/', user_list, name='user_list'),
    path('users/<int:user_id>/', user_detail, name='user_detail'),

    path('password-change/', UserPasswordChange.as_view(), name="password_change"),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name="password_change_done"),

    path('password-reset/',
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),

]

TransHub/transport/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from main.models import Country,City, Region
import math
from django.utils.timezone import now


class Transport(models.Model):

    class Status(models.IntegerChoices):
        UNABLE = 0, 'Недоступний'
        ABLE = 1, 'Доступний'

    STATUS_CHOICES = [
        ('Search', 'Searching'),
        ('IN_TRANSIT', 'In Transit'),
        ('Busy', 'Busy'),
    ]

    loading_date = models.DateField()
    country_from = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, related_name='country_from_tr',
                                     verbose_name="Країна віправлення")
    region_from = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True, related_name='region_from_tr',
                                    verbose_name="Регіон віправлення")
    city_from = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, related_name='city_from_tr',
                                  verbose_name="Місто віправлення")

    country_to = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, related_name='country_to_tr',
                                   verbose_name="Країна призанчення")
    region_to = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True, related_name='region_to_tr',
                                  verbose_name="Регіон призанчення")
    city_to = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, related_name='city_to_tr',
                                verbose_name="Місто призанчення")

    brand = models.CharField(max_length=100, verbose_name="Бренд")
    model = models.CharField(max_length=100, verbose_name="Модель")
    license_plate = models.CharField(max_length=8, unique=True, verbose_name="Номерний знак")
    year = models.PositiveIntegerField(verbose_name="Рік випуску",validators=[MinValueValidator(1950), MaxValueValidator(2024)])
    max_weight = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Максимальна вага (кг)",)
    max_volume = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Максимальний об'єм (м³)")

    body_type = models.ManyToManyField('BodyType', verbose_name="Тип кузова", related_name='body_type')
    load_unload = models.ManyToManyField('LoadUnload',verbose_name="Завантаження/Розвантаження", related_name='load_unload')
    permissions = models.ManyToManyField('Permissions',verbose_name="Дозволи", related_name='permissions')

    photo = models.ImageField(upload_to='transport_photos/%Y/%m/%d/', blank=True, verbose_name="Фото")
    notes = models.TextField(blank=True, verbose_name="Примітки")
    published = models.BooleanField(choices=tuple(map(lambda x: (bool(x[0]), x[1]), Status.choices)), default=Status.ABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата створення")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата оновлення")

    freeze = models.BooleanField(default=False, verbose_name="Заморожування")

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Search', verbose_name="Статус")
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, default=None, related_name='author1')

    class Meta:
        verbose_name = "Транпорт"
        verbose_name_plural = "Транпорт"

    def get_absolute_url(self):
        return reverse('transport:detail', kwargs={"tr_pk": self.pk})

    def get_distance(self):
        R = 6371.0
        city1 = City.objects.get(id=self.city_from.id)
        city2 = City.objects.get(id=self.city_to.id)
        if city1 == city2:
            return 10
        lat1 = city1.latitude
        lon1 = city1.longitude
        lat2 = city2.latitude
        lon2 = city2.longitude

        lat1 = math.radians(lat1)
        lon1 = math.radians(lon1)
        lat2 = math.radians(lat2)
        lon2 = math.radians(lon2)

        dlat = lat2 - lat1
        dlon = lon2 - lon1


        a = math.sin(dlat / 2) ** 2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2) ** 2
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

        distance = R * c
        return round(distance,2)

    def get_time(self):
        delta = now() - self.updated_at
        seconds = delta.total_seconds()

        if seconds < 60:
            return f"{int(seconds)} секунд тому"
        elif seconds < 3600:
            minutes = seconds // 60
            return f"{int(minutes)} хвилин тому"
        elif seconds < 86400:
            hours = seconds // 3600
            return f"{int(hours)} годин тому"
        else:
            days = seconds // 86400
            return f"{int(days)} днів тому"

class LoadUnload(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Permissions(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class BodyType(models.Model):
    slug = models.SlugField(max_length=100, unique=True)
    name = models.CharField(max_length=100)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

TransHub/transport/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, FormView, TemplateView, UpdateView
from django.urls import reverse_lazy
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin

from .utils import *
from .models import *
from .forms import *
from main.models import City, Region


def load_regions(request):
    country_id = request.GET.get('country_id')
    if country_id:
        regions = Region.objects.filter(country_id=country_id).order_by('name')
        return render(request, 'transport/region_dropdown_list_options.html', {'regions': regions})
    return render(request, 'transport/region_dropdown_list_options.html', {'regions': Region.objects.none()})


def load_cities(request):
    region_id = request.GET.get('region_id')
    if region_id:
        cities = City.objects.filter(region_id=region_id).order_by('name')
        return render(request, 'transport/city_dropdown_list_options.html', {'cities': cities})
    return render(request, 'transport/city_dropdown_list_options.html', {'cities': City.objects.none()})


class AddTransport(LoginRequiredMixin, DataMixin, CreateView):
    form_class = TransportForm
    template_name = 'transport/add_transport.html'

    def form_valid(self, form):
        w = form.save(commit=False)
        w.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Додати транспорт')
        return dict(list(context.items()) + list(c_def.items()))

    def get_success_url(self):
        return reverse_lazy('transport:my_transport')


class AllTransport(LoginRequiredMixin, DataMixin, ListView):
    paginate_by = 50
    model = Transport
    template_name = 'transport/all_transport.html'
    form_class = TranportFilterForm
    context_object_name = 'transports'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Пошук Транспорту')
        form = self.form_class(self.request.GET or None)
        context['form'] = form
        return dict(list(context.items())+list(c_def.items()))

    def get_queryset(self):
        queryset = Transport.objects.order_by('-updated_at').filter(published=True, status='Search',freeze=False).exclude(
            author_id=self.request.user.pk).select_related("author").prefetch_related('body_type', 'load_unload', 'permissions')
        form = self.form_class(self.request.GET or None)

        # Якщо форма валідна, застосовуємо фільтри
        if form.is_valid():
            country_from = form.cleaned_data.get('country_from')
            region_from = form.cleaned_data.get('region_from')
            city_from = form.cleaned_data.get('city_from')
            country_to = form.cleaned_data.get('country_to')
            region_to = form.cleaned_data.get('region_to')
            city_to = form.cleaned_data.get('city_to')
            weight_max = form.cleaned_data.get('weight_max')
            volume_max = form.cleaned_data.get('volume_max')
            body_type = form.cleaned_data.get('body_type')
            load_unload = form.cleaned_data.get('load_unload')

            # Применение фильтров на основе заполненных полей
            if country_from:
                queryset = queryset.filter(country_from=country_from)
            if region_from:
                queryset = queryset.filter(region_from=region_from)
            if city_from:
                queryset = queryset.filter(city_from=city_from)
            if country_to:
                queryset = queryset.filter(country_to=country_to)
            if region_to:
                queryset = queryset.filter(region_to=region_to)
            if city_to:
                queryset = queryset.filter(city_to=city_to)
            if weight_max:
                queryset = queryset.filter(weight_max__lte=weight_max)
            if volume_max:
                queryset = queryset.filter(volume_max__lte=volume_max)
            if body_type:
                queryset = queryset.filter(body_type__in=body_type)
            if load_unload:
                queryset = queryset.filter(load_unload__in=load_unload)

        return queryset


class MYTransport(LoginRequiredMixin, DataMixin, ListView):
    paginate_by = 50
    model = Transport
    template_name = 'transport/my_transport2.html'
    context_object_name = 'transports'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Мій транспорт')
        return dict(list(context.items())+list(c_def.items()))

    def get_queryset(self):
        id_user = self.request.user.pk
        return Transport.objects.filter(author=id_user).order_by('-status','published','-updated_at' ).prefetch_related('body_type','load_unload','permissions')


class Transport_update(LoginRequiredMixin,DataMixin, UpdateView):
    model = Transport
    form_class = TransportForm
    template_name = 'transport/add_transport.html'

    def get_object(self, queryset=None):
        transport = super().get_object(queryset)
        if transport.author != self.request.user:
            raise Http404("Transport not found.")
        return transport

    def get_success_url(self):
        return reverse_lazy('transport:my_transport')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Оновити Інформацію про Транспорт')
        return dict(list(context.items())+list(c_def.items()))

class ShowTr(LoginRequiredMixin, DataMixin, DetailView):
    model = Transport
    template_name = 'transport/one_transport.html'
    pk_url_kwarg = 'tr_pk'
    context_object_name = 'transport'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title=context['transport'])
        return dict(list(context.items()) + list(c_def.items()))

TransHub/transport/templates/transport/add_transport.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container w-75 ">
    <h1 class="h3 mb-3 fw-normal">{{title}}</h1>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors}}</div>

           <div class="row" align="center">
        <div class="col-md-6">

            {{ form.country_from.label_tag }}
            {{ form.country_from }}
            <div class="form-error">{{ form.country_from.errors }}</div>

            {{ form.region_from.label_tag }}
            {{ form.region_from  }}
            <div class="form-error">{{ form.region_from.errors }}</div>

            {{ form.city_from.label_tag }}
            {{ form.city_from }}
            <div class="form-error">{{ form.city_from.errors }}</div>
        </div>

        <div class="col-md-6">

            {{ form.country_to.label_tag }}
            {{ form.country_to }}
            <div class="form-error">{{ form.country_to.errors }}</div>

            {{ form.region_to.label_tag }}
            {{ form.region_to}}
            <div class="form-error">{{ form.region_to.errors }}</div>

            {{ form.city_to.label_tag }}
            {{ form.city_to }}
            <div class="form-error">{{ form.city_to.errors }}</div>

        </div>
    </div>

        <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                {{ form.loading_date.label_tag }}
                {{ form.loading_date }}
            </div>

        </div>
        <div class="col-md-4">
            <div class="form-group">
                {{ form.max_weight.label_tag }}
                {{ form.max_weight }}
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                {{ form.max_volume.label_tag }}
                {{ form.max_volume }}
            </div>
        </div>
        </div>

    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                {{ form.brand.label_tag }}
                {{ form.brand }}
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                {{ form.model.label_tag }}
                {{ form.model }}
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                {{ form.license_plate.label_tag }}
                {{ form.license_plate }}
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                {{ form.year.label_tag }}
                {{ form.year }}
            </div>
        </div>
    </div>

        <div class="row">


        <div class="col-md-4">
            <div class="form-group">
                {{ form.body_type.label_tag }}
                 {{ form.body_type }}
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                {{ form.load_unload.label_tag }}
                 {{ form.load_unload}}
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                {{ form.permissions.label_tag }}
                 {{ form.permissions }}
            </div>
        </div>
    </div>

            <div class="form-group">
                {{ form.photo.label_tag }}
                {{ form.photo }}
            </div>

            <div class="form-group">
                {{ form.notes.label_tag }}
                {{ form.notes }}
            </div>

            <div class="form-group " align="center">
                {{ form.published.label_tag }}
                {{ form.published }}
            </div>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script>

    $('#id_country_from').change(function() {
        var url = "{% url 'transport:load_regions' %}";
        var countryId = $(this).val();
        $.ajax({
            url: url,
            data: {
                'country_id': countryId
            },
            success: function(data) {
                $("#id_region_from").html(data);
            }
        });
    });

    $('#id_region_from').change(function() {
        var url = "{% url 'transport:load_cities' %}";
        var regionId = $(this).val();
        $.ajax({
            url: url,
            data: {
                'region_id': regionId
            },
            success: function(data) {
                $("#id_city_from").html(data);
            }
        });
    });


    $('#id_country_to').change(function() {
        var url = "{% url 'transport:load_regions' %}";
        var countryId = $(this).val();
        $.ajax({
            url: url,
            data: {
                'country_id': countryId
            },
            success: function(data) {
                $("#id_region_to").html(data);
            }
        });
    });

    $('#id_region_to').change(function() {
        var url = "{% url 'transport:load_cities' %}";
        var regionId = $(this).val();
        $.ajax({
            url: url,
            data: {
                'region_id': regionId
            },
            success: function(data) {
                $("#id_city_to").html(data);
            }
        });
    });
</script>
        <button type="submit" class="btn btn-primary">Додати транспорт</button>

    </form>
</div>

{% endblock %}

TransHub/transport/templates/transport/all_transport.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container mt-5">

    <div class="container w-75" style="background-color: honeydew; border-radius: 40px; ">
    <form method="get" class="m-4">
         <div class="row">
        <div class="col-md-3">
            {{ form.country_from.label_tag }}
            {{ form.country_from }}
            <div class="form-error">{{ form.country_from.errors }}</div>
        </div>
        <div class="col-md-3">
            {{ form.country_to.label_tag }}
            {{ form.country_to }}
            <div class="form-error">{{ form.country_to.errors }}</div>
        </div>
         <div class="col-md-3">
            {{ form.max_weight.label_tag }}
            {{ form.max_weight}}
            <div class="form-error">{{ form.max_weight.errors }}</div>
        </div>
         <div class="col-md-3">
            {{ form.max_volume.label_tag }}
            {{ form.max_volume }}
            <div class="form-error">{{ form.max_volume.errors }}</div>
        </div>
    </div>

       <div class="row" align="center">
        <div class="col-md-3">
            {{ form.region_from.label_tag }}
            {{ form.region_from  }}
            <div class="form-error">{{ form.region_from.errors }}</div>

            {{ form.city_from.label_tag }}
            {{ form.city_from }}
            <div class="form-error">{{ form.city_from.errors }}</div>
        </div>

        <div class="col-md-3">
            {{ form.region_to.label_tag }}
            {{ form.region_to}}
            <div class="form-error">{{ form.region_to.errors }}</div>

            {{ form.city_to.label_tag }}
            {{ form.city_to }}
            <div class="form-error">{{ form.city_to.errors }}</div>

        </div>
        <div class="col-md-3">
            {{ form.load_unload.label_tag }}
            {{ form.load_unload  }}
            <div class="form-error">{{ form.load_unload.errors }}</div>
        </div>
        <div class="col-md-3">
            {{ form.body_type.label_tag }}
            {{ form.body_type }}
            <div class="form-error">{{ form.body_type.errors }}</div>
        </div>
    </div>

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $('#id_country_from').change(function() {
        var url = "{% url 'transport:load_regions' %}";
        var countryId = $(this).val();
        $.ajax({
            url: url,
            data: {
                'country_id': countryId
            },
            success: function(data) {
                $("#id_region_from").html(data);
            }
        });
    });

    $('#id_region_from').change(function() {
        var url = "{% url 'transport:load_cities' %}";
        var regionId = $(this).val();
        $.ajax({
            url: url,
            data: {
                'region_id': regionId
            },
            success: function(data) {
                $("#id_city_from").html(data);
            }
        });
    });

    $('#id_country_to').change(function() {
        var url = "{% url 'transport:load_regions' %}";
        var countryId = $(this).val();
        $.ajax({
            url: url,
            data: {
                'country_id': countryId
            },
            success: function(data) {
                $("#id_region_to").html(data);
            }
        });
    });

    $('#id_region_to').change(function() {
        var url = "{% url 'transport:load_cities' %}";
        var regionId = $(this).val();
        $.ajax({
            url: url,
            data: {
                'region_id': regionId
            },
            success: function(data) {
                $("#id_city_to").html(data);
            }
        });
    });
</script>
    <div align="center" class="mt-2">
        <button type="submit" class="btn btn-secondary rounded-pill px-3">Фільтрувати</button>
    </div>
    </form>
    </div>

     {% for cargo in transports %}

    <div class="container2">
        <div class="card">
            <div class="card-header2">
                <div class="left">
                    <i class="fas fa-clock"></i>
                    <span>{{ cargo.get_time }}</span>
                </div>
                <div class="right">
                    <div class="price">Дата завантаження: {{ cargo.loading_date }}</div>
                    <div class="tags">
                        {% for item in cargo.body_type.all %}
                        <span>{{ item.name }}</span>
                        {% endfor %}
                        <br>
                        Тип Завантаження:
                        {% for item in cargo.load_unload.all %}
                        <span>{{ item.name }}</span>
                        {% endfor %}
                        Дозволи:
                        {% for item in cargo.permissions.all %}
                        <span>{{ item.name }}</span>
                        {% endfor %}

                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="route">{{ cargo.country_from }}-{{ cargo.region_from }}-{{ cargo.city_from }} ---> {{ cargo.country_to }}-{{ cargo.region_to }}-{{ cargo.city_to }} — {{ cargo.get_distance }} км
                    <br>
                    {{ cargo.title }}
                </div>
                <div class="details">
                    <span>{{ cargo.max_weight }} кг</span>
                    <span>{{ cargo.max_volume }} м³</span>


                </div>
                <div class="details">
                    <span> Примітки: {{ cargo.notes}}</span>

                </div>
                <div class="right2">
                    <div align="center" >
                                        {% if cargo.photo and cargo.photo.url %}
                                    <img alt="фото транспорту" width="200" height="100"  src="{{cargo.photo.url}}">
                                    {% endif %}
                    </div>
                    <span>Створено о {{ cargo.created_at }}</span>
                    <br>
                    <span>Оновлено о {{ cargo.updated_at }}</span>
                </div>

                <div class="company">{{ cargo.author.name_company }}
                    <div class="star-rating">
                        <div class="stars-outer">
                            <div class="stars-inner" style="width: {{ cargo.author.rating|floatformat:0 }}%;"></div>
                        </div>
                    </div>
                </div>

                <a href="{% url 'users:user_detail' cargo.author.id %}" style="color:green">Детальніше о перевізнику</a>

                <div class="contact">
                    <i class="fas fa-user"></i>
                    <span>{{ cargo.author.get_full_name }}</span>

                </div>
                <div class="contact">
                    <i class="fas fa-phone"></i>
                    <a href="tel:{{ cargo.author.tel }}">{{ cargo.author.tel }}</a>
                </div>
                <div class="contact">
                    <i class="fas fa-envelope"></i>
                    <a href="mailto:{{ cargo.author.email }}">{{ cargo.author.email }}</a>
                </div>

                </div>


            </div>
    </div>
        {% endfor %}

</div>
{% endblock %}

TransHub/transport/templates/transport/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.id }}">{{ city.name }}</option>
{% endfor %}

TransHub/transport/templates/transport/region_dropdown_list_options.html
<option value="">---------</option>
{% for region in regions %}
<option value="{{ region.id }}">{{ region.name }}</option>
{% endfor %}