TransHub/TransHub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from TransHub import settings
from main.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('cargo/', include('cargo.urls', namespace='cargo')),
    path('transport/', include('transport.urls', namespace='transport')),
    path('', include('main.urls')),
]
"""
if settings.DEBUG:
    import debug_toolbar
    urlpatterns=[
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    """
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TransHub/cargo/urls.py
from django.urls import path,include
from .views import *
app_name = 'cargo'

urlpatterns = [
    path('add_cargo/', AddCargo.as_view(), name='add_cargo'),
    path('all_cargo/', AllCargo.as_view(), name='all_cargo'),
    path('my_cargo/', MYCargo.as_view(), name='my_cargo'),
    path('ajax/load-regions/', load_regions, name='load_regions'),
    path('ajax/load-cities/', load_cities, name='load_cities'),
    path('update/<int:pk>/', Cargo_update.as_view(), name='update'),
]

TransHub/main/urls.py
from django.urls import path,include
from .views import *

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('logout/', logout_user, name='logout'),
    path('log/', MainLogin.as_view(), name='log_good'),
    path('about/', About.as_view(), name='about'),
    path('about_cargo/', About_Cargo.as_view(), name='about_cargo'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('take_cargo/', take_cargo, name='take_cargo'),
    path('freeze_cargo/', freeze_cargo_tr, name='freeze_cargo'),
    path('delivered_cargo/', delivered_cargo, name='delivered_cargo'),
    path('unfreeze_cargo/', un_freeze_cargo_tr, name='un_freeze'),
    path('unfreeze_tr/', un_freeze_tr, name='un_freeze_tr'),
    path('create_docs/', create_docs, name='create_docs'),
    path('my_docs/', MYDoc.as_view(), name='my_doc'),
    path('download/<str:file_type>/<int:event_id>/',download_file, name='download_file'),

]

TransHub/users/urls.py
from django.urls import path,include
from django.views.decorators.cache import cache_page
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .views import *

app_name = 'users'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('rev/', ReviewView.as_view(), name='rev'),
    path('com/', ComplaintView.as_view(), name='com'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('profile/', ProfileUser.as_view(), name='profile'),
    path('profiles/', user_list, name='user_list'),
    path('users/<int:user_id>/', user_detail, name='user_detail'),

    path('password-change/', UserPasswordChange.as_view(), name="password_change"),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name="password_change_done"),

    path('password-reset/',
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),

]

TransHub/cargo/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from main.models import Country, City, Region

from django.utils.timezone import now
import math


class Cargo(models.Model):

    class Status(models.IntegerChoices):
        DRAFT = 0, 'Черновик'
        PUBLISHED = 1, 'Опубліковано'

    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('IN_TRANSIT', 'In Transit'),
        ('DELIVERED', 'Delivered'),
    ]

    PACKAGING_CHOICES = [
        ('Без упаковки', 'Без упакування'),
        ('EURO 1,2x0,8 м', 'EURO 1,2x0,8 м'),
        ('FIN 1,2x1 м', 'FIN 1,2x1 м'),
        ('1x1 м', '1x1 м'),
        ('1,1x1,1 м', '1,1x1,1 м'),
        ('1,2x1,2 м', '1,2x1,2 м'),
        ('Нестандартна', 'Нестандартна'),
        ('Біг-бег', 'Біг-бег'),
        ('Мішок', 'Мішок'),
        ('В’язка', 'В’язка'),
        ('Сітка', 'Сітка'),
        ('Тюк', 'Тюк'),
        ('Блок', 'Блок'),
        ('Бочка', 'Бочка'),
        ('Чушка', 'Чушка'),
        ('Ящик', 'Ящик'),
        ('Коробка', 'Коробка'),
        ('Пачка', 'Пачка'),
        ('Упаковка', 'Упаковка'),
        ('Swap body', 'Swap body'),
        ("45'", "45'"),
        ("40'", "40'"),
        ("20'", "20'"),
        ('Бухта', 'Бухта'),
        ('Рулон', 'Рулон'),
        ('Барабан', 'Барабан'),
        ('Балон', 'Балон'),
        ('Каністра', 'Каністра'),
        ('Відро', 'Відро'),
        ('Навалом', 'Навалом'),
        ('Насипом', 'Насипом')
    ]

    PAYMENT_TYPE2_CHOICES = [
        ('CASH', 'готівка'),
        ('BANK', 'безготівка'),
        ('COMBO', 'комб.'),
        ('ELEC', 'ел. платіж'),
        ('CARD', 'картка'),
    ]

    PAYMENT_MOMENT_CHOICES = [
        ('LOAD', 'На загрузці'),
        ('UNLOAD', 'На вигрузці'),
        ('ORIGINALS', 'По оригіналам'),
        ('DEFERRED', 'Відсрочка оплати'),
    ]

    title = models.CharField(max_length=100, verbose_name="Назва вантажу")

    country_from = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, related_name='country_from_cargos',
                                     verbose_name="Країна віправлення")
    region_from = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True, related_name='region_from_cargos',
                                    verbose_name="Регіон віправлення")
    city_from = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, related_name='city_from_cargos',
                                  verbose_name="Місто віправлення")

    country_to = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, related_name='country_to_cargos',
                                   verbose_name="Країна призанчення")
    region_to = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True, related_name='region_to_cargos',
                                  verbose_name="Регіон призанчення")
    city_to = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, related_name='city_to_cargos',
                                verbose_name="Місто призанчення")

    weight_max = models.PositiveIntegerField(verbose_name="Вага до (кг)", validators=[MinValueValidator(1)])
    volume_max = models.PositiveIntegerField(verbose_name="Об'єм до (м³)", null=True, validators=[MinValueValidator(1)])
    length = models.DecimalField(max_digits=4, decimal_places=2, verbose_name="Довжина (м)",
                                 validators=[MinValueValidator(0.01), MaxValueValidator(99.99)], null=True)
    width = models.DecimalField(max_digits=4, decimal_places=2, verbose_name="Ширина (м)",
                                validators=[MinValueValidator(0.01), MaxValueValidator(99.99)], null=True)
    height = models.DecimalField(max_digits=4, decimal_places=2, verbose_name="Висота (м)",
                                 validators=[MinValueValidator(0.01), MaxValueValidator(99.99)], null=True)
    packaging = models.CharField(max_length=100, choices=PACKAGING_CHOICES, verbose_name="Пакування")
    body_type = models.ManyToManyField('BodyType', verbose_name="Тип кузова", related_name='body_type')
    load_unload = models.ManyToManyField('LoadUnload', verbose_name="Завантаження/Розвантаження",
                                         related_name='load_unload')
    permissions = models.ManyToManyField('Permissions', verbose_name="Дозволи", related_name='permissions')
    payment_type = models.CharField(max_length=100, choices=PAYMENT_TYPE2_CHOICES, verbose_name="Форма оплати",
                                    default='default')
    amount = models.PositiveIntegerField(verbose_name="Сума коштів", blank=True, null=True)
    currency = models.CharField(max_length=10, verbose_name="Валюта", default='грн')
    payment_moment = models.CharField(max_length=100, choices=PAYMENT_MOMENT_CHOICES, verbose_name="Момент оплати")
    photo = models.ImageField(upload_to='cargo_photos/%Y/%m/%d/', blank=True, verbose_name="Фото")
    notes = models.TextField(blank=True, verbose_name="Примітка")
    published = models.BooleanField(choices=tuple(map(lambda x: (bool(x[0]), x[1]), Status.choices)),
                                    default=Status.DRAFT, verbose_name="Опубліковано")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата створення")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата оновлення")

    freeze = models.BooleanField(default=False, verbose_name="Заморожування")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING', verbose_name="Статус")
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL,
                               null=True, default=None, related_name='author')

    class Meta:
        verbose_name = "Вантаж"
        verbose_name_plural = "Вантажи"

    def get_absolute_url(self):
        return reverse('home')

    def get_distance(self):
        R = 6371.0
        city1 = City.objects.get(id=self.city_from.id)
        city2 = City.objects.get(id=self.city_to.id)
        if city1 == city2:
            return 10
        lat1 = city1.latitude
        lon1 = city1.longitude
        lat2 = city2.latitude
        lon2 = city2.longitude

        lat1 = math.radians(lat1)
        lon1 = math.radians(lon1)
        lat2 = math.radians(lat2)
        lon2 = math.radians(lon2)

        dlat = lat2 - lat1
        dlon = lon2 - lon1

        a = math.sin(dlat / 2) ** 2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2) ** 2
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

        distance = R * c
        return round(distance,2)

    def get_per_km(self):
        a = self.amount / self.get_distance()
        return round(a,2)

    def get_time(self):
        delta = now() - self.updated_at
        seconds = delta.total_seconds()

        if seconds < 60:
            return f"{int(seconds)} секунд тому"
        elif seconds < 3600:
            minutes = seconds // 60
            return f"{int(minutes)} хвилин тому"
        elif seconds < 86400:
            hours = seconds // 3600
            return f"{int(hours)} годин тому"
        else:
            days = seconds // 86400
            return f"{int(days)} днів тому"


class LoadUnload(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Permissions(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class BodyType(models.Model):
    slug = models.SlugField(max_length=100, unique=True)
    name = models.CharField(max_length=100)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

TransHub/cargo/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, FormView, TemplateView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404

from .models import *
from .forms import *
from .utils import *
from main.models import City, Region, Event

from django.http import JsonResponse

def load_regions(request):
    country_id = request.GET.get('country_id')
    if country_id:
        regions = Region.objects.filter(country_id=country_id).order_by('name')
        return render(request, 'cargo/region_dropdown_list_options.html', {'regions': regions})
    return render(request, 'cargo/region_dropdown_list_options.html', {'regions': Region.objects.none()})


def load_cities(request):
    region_id = request.GET.get('region_id')
    if region_id:
        cities = City.objects.filter(region_id=region_id).order_by('name')
        return render(request, 'cargo/city_dropdown_list_options.html', {'cities': cities})
    return render(request, 'cargo/region_dropdown_list_options.html', {'regions': City.objects.none()})


class AddCargo(LoginRequiredMixin, DataMixin, CreateView):
    form_class = CargoForm
    template_name = 'cargo/add_cargo.html'

    def form_valid(self, form):
        w = form.save(commit=False)
        w.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Додати вантаж')
        return dict(list(context.items()) + list(c_def.items()))

    def get_success_url(self):
        return reverse_lazy('cargo:my_cargo')


class AllCargo(LoginRequiredMixin, DataMixin2, ListView):
    paginate_by = 50
    model = Cargo
    template_name = 'cargo/all_cargo2.html'
    form_class = CargoFilterForm
    context_object_name = 'cargos'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Пошук вантажу')
        form = self.form_class(self.request.GET or None)
        context['form'] = form
        return dict(list(context.items())+list(c_def.items()))

    def get_queryset(self):
        queryset = Cargo.objects.order_by('-updated_at').filter(published=True, status='PENDING',freeze=False).exclude(
            author_id=self.request.user.pk).select_related("author").prefetch_related('body_type', 'load_unload', 'permissions')
        form = self.form_class(self.request.GET or None)

        # Якщо форма валідна, застосовуємо фільтри
        if form.is_valid():
            country_from = form.cleaned_data.get('country_from')
            region_from = form.cleaned_data.get('region_from')
            city_from = form.cleaned_data.get('city_from')
            country_to = form.cleaned_data.get('country_to')
            region_to = form.cleaned_data.get('region_to')
            city_to = form.cleaned_data.get('city_to')
            weight_max = form.cleaned_data.get('weight_max')
            volume_max = form.cleaned_data.get('volume_max')
            body_type = form.cleaned_data.get('body_type')
            load_unload = form.cleaned_data.get('load_unload')

            # Применение фильтров на основе заполненных полей
            if country_from:
                queryset = queryset.filter(country_from=country_from)
            if region_from:
                queryset = queryset.filter(region_from=region_from)
            if city_from:
                queryset = queryset.filter(city_from=city_from)
            if country_to:
                queryset = queryset.filter(country_to=country_to)
            if region_to:
                queryset = queryset.filter(region_to=region_to)
            if city_to:
                queryset = queryset.filter(city_to=city_to)
            if weight_max:
                queryset = queryset.filter(weight_max__lte=weight_max)
            if volume_max:
                queryset = queryset.filter(volume_max__lte=volume_max)
            if body_type:
                queryset = queryset.filter(body_type__in=body_type)
            if load_unload:
                queryset = queryset.filter(load_unload__in=load_unload)

        return queryset


class MYCargo(LoginRequiredMixin, DataMixin, ListView):
    paginate_by = 50
    model = Cargo
    template_name = 'cargo/my_cargo.html'
    context_object_name = 'cargos'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Мій вантаж')
        return dict(list(context.items())+list(c_def.items()))

    def get_queryset(self):
        id_user = self.request.user.pk
        return Cargo.objects.order_by('-status','published','-updated_at' ).filter(author=id_user).prefetch_related('body_type','load_unload','permissions')

class Cargo_update(LoginRequiredMixin,DataMixin, UpdateView):
    model = Cargo
    form_class = CargoForm
    template_name = 'cargo/add_cargo.html'

    def get_object(self, queryset=None):
        cargo = super().get_object(queryset)
        if cargo.author != self.request.user:
            raise Http404("Cargo not found.")
        return cargo

    def get_success_url(self):
        return reverse_lazy('cargo:my_cargo')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Оновити Інформацію про вантаж')
        return dict(list(context.items())+list(c_def.items()))

TransHub/cargo/templates/cargo/all_cargo2.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container mt-5" >

   <div class="container w-75" style="background-color: honeydew; border-radius: 40px; ">
    <form method="get" class="m-4">
         <div class="row">
        <div class="col-md-3">
            {{ form.country_from.label_tag }}
            {{ form.country_from }}
            <div class="form-error">{{ form.country_from.errors }}</div>
        </div>
        <div class="col-md-3">
            {{ form.country_to.label_tag }}
            {{ form.country_to }}
            <div class="form-error">{{ form.country_to.errors }}</div>
        </div>
         <div class="col-md-3">
            {{ form.weight_max.label_tag }}
            {{ form.weight_max}}
            <div class="form-error">{{ form.weight_max.errors }}</div>
        </div>
         <div class="col-md-3">
            {{ form.volume_max.label_tag }}
            {{ form.volume_max }}
            <div class="form-error">{{ form.volume_max.errors }}</div>
        </div>
    </div>

       <div class="row" align="center">
        <div class="col-md-3">
            {{ form.region_from.label_tag }}
            {{ form.region_from  }}
            <div class="form-error">{{ form.region_from.errors }}</div>

            {{ form.city_from.label_tag }}
            {{ form.city_from }}
            <div class="form-error">{{ form.city_from.errors }}</div>
        </div>

        <div class="col-md-3">
            {{ form.region_to.label_tag }}
            {{ form.region_to}}
            <div class="form-error">{{ form.region_to.errors }}</div>

            {{ form.city_to.label_tag }}
            {{ form.city_to }}
            <div class="form-error">{{ form.city_to.errors }}</div>

        </div>
        <div class="col-md-3">
            {{ form.load_unload.label_tag }}
            {{ form.load_unload  }}
            <div class="form-error">{{ form.load_unload.errors }}</div>
        </div>
        <div class="col-md-3">
            {{ form.body_type.label_tag }}
            {{ form.body_type }}
            <div class="form-error">{{ form.body_type.errors }}</div>
        </div>
    </div>

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $('#id_country_from').change(function() {
        var url = "{% url 'cargo:load_regions' %}";
        var countryId = $(this).val();
        $.ajax({
            url: url,
            data: {
                'country_id': countryId
            },
            success: function(data) {
                $("#id_region_from").html(data);
            }
        });
    });

    $('#id_region_from').change(function() {
        var url = "{% url 'cargo:load_cities' %}";
        var regionId = $(this).val();
        $.ajax({
            url: url,
            data: {
                'region_id': regionId
            },
            success: function(data) {
                $("#id_city_from").html(data);
            }
        });
    });

    $('#id_country_to').change(function() {
        var url = "{% url 'cargo:load_regions' %}";
        var countryId = $(this).val();
        $.ajax({
            url: url,
            data: {
                'country_id': countryId
            },
            success: function(data) {
                $("#id_region_to").html(data);
            }
        });
    });

    $('#id_region_to').change(function() {
        var url = "{% url 'cargo:load_cities' %}";
        var regionId = $(this).val();
        $.ajax({
            url: url,
            data: {
                'region_id': regionId
            },
            success: function(data) {
                $("#id_city_to").html(data);
            }
        });
    });
</script>
    <div align="center" class="mt-2">
        <button type="submit" class="btn btn-secondary rounded-pill px-3">Фільтрувати</button>
    </div>
    </form>
    </div>
     {% for cargo in cargos %}

    <div class="container2">

        <div class="card">
            <div class="card-header2">
                <div class="left">
                    <i class="fas fa-clock"></i>
                    <span>{{ cargo.get_time }}</span>
                </div>
                <div class="right">
                    <div class="price">{{ cargo.amount }} {{ cargo.currency}}</div>
                    <div class="price-per-km">{{ cargo.get_per_km }} грн/км</div>
                    <div class="tags">
                        <span>{{ cargo.get_payment_type_display }}</span>
                        <span>{{ cargo.get_payment_moment_display }}</span>
                        {% for item in cargo.body_type.all %}
                        <span>{{ item.name }}</span>
                        {% endfor %}
                        <br>
                        Тип Завантаження:
                        {% for item in cargo.load_unload.all %}
                        <span>{{ item.name }}</span>
                        {% endfor %}
                        Дозволи:
                        {% for item in cargo.permissions.all %}
                        <span>{{ item.name }}</span>
                        {% endfor %}
                        
                        
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="route">{{ cargo.country_from }}-{{ cargo.region_from }}-{{ cargo.city_from }} ---> {{ cargo.country_to }}-{{ cargo.region_to }}-{{ cargo.city_to }} — {{ cargo.get_distance }} км
                    <br>
                    {{ cargo.title }}
                </div>
                <div class="details">                   
                    <span>{{ cargo.weight_max }} кг</span>
                    <span>{{ cargo.volume_max }} м³</span>
                    <span>ДШВ: {{ cargo.length }} м,{{ cargo.width }} м,{{ cargo.height }} м</span>
                    
                </div>
                <div class="details">
                    <span>Пакування: {{ cargo.get_packaging_display }}</span>
                    <span> Примітки: {{ cargo.notes}}</span> 

                </div>
                <div class="company">{{ cargo.author.name_company }}
                    <div class="star-rating">
                        <div class="stars-outer">
                            <div class="stars-inner" style="width: {{ cargo.author.rating|floatformat:0 }}%;"></div>
                        </div>
                    </div>
                </div>

                <a href="{% url 'users:user_detail' cargo.author.id %}" style="color:green">Детальніше о відправнику</a>

                <div class="contact">
                    <i class="fas fa-user"></i>
                    <span>{{ cargo.author.first_name }} {{ cargo.author.last_name }} {{ cargo.author.third_name }}</span>

                </div>
                <div class="contact">
                    <i class="fas fa-phone"></i>
                    <a href="tel:{{ cargo.author.tel }}">{{ cargo.author.tel }}</a>
                </div>
                <div class="contact">
                    <i class="fas fa-envelope"></i>                   
                    <a href="mailto:{{ cargo.author.email }}">{{ cargo.author.email }}</a>
                </div>

                <div class="right2">
                    <div align="center" >
                                        {% if cargo.photo and cargo.photo.url %}
                                    <img alt="фото транспорту" width="200" height="100"  src="{{cargo.photo.url}}">
                                    {% endif %}
                    </div>
                    <span>Створено о {{ cargo.created_at }}</span>
                    <br>
                    <span>Оновлено о {{ cargo.updated_at }}</span>
                </div>
            </div>
            {% if user_transport %}
                <form method="post" action="{% url 'freeze_cargo'%}">
                    {% csrf_token %}
                    <select name="transport_id">
                        {% for transport in user_transport %}
                            <option value="{{ transport.id }}">{{ transport.brand}}_{{ transport.model }}, {{ transport.license_plate }}, {{ transport.year }} </option>
                        {% endfor %}
                    </select>
                    <input type="hidden" name="cargo_id" value="{{ cargo.id }}">

                    <button type="submit" class="btn btn-success rounded-pill px-3">Взяти вантаж</button>
                </form>
            {% endif %}

        </div>
    </div>
        {% endfor %}

     </div>
{% endblock %}

TransHub/cargo/templates/cargo/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.id }}">{{ city.name }}</option>
{% endfor %}

TransHub/cargo/templates/cargo/region_dropdown_list_options.html
<option value="">---------</option>
{% for region in regions %}
<option value="{{ region.id }}">{{ region.name }}</option>
{% endfor %}